# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlightBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlightBuddy
  pod 'SwiftVideoBackground'
  pod 'BarcodeScanner'
  pod 'PKHUD'

end
